# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='No description provided.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_depart', models.DateTimeField()),
                ('date_return', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('salt', models.CharField(max_length=255)),
                ('pw', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='planned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_planned', to='travel_buddy.User'),
        ),
        migrations.AddField(
            model_name='destination',
            name='travelers',
            field=models.ManyToManyField(related_name='destinations', to='travel_buddy.User'),
        ),
    ]
