# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_auto_20180420_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='date_depart',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='date_return',
            field=models.DateField(),
        ),
    ]
